# Generated by Django 5.0.dev20230711121319 on 2023-07-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
#Migrations are used to MIGRATE the MODEL (models.py) to the database, from there the database creates a table based 
#on the model you specified in (models.py)
#To make migrations, run this command "python manage.py makemigrations [file name ex: myapp]"

#Each set of changes we make to a database is saved in a sequntially ordered file to migrate smoothly between 
#schema changes

#TO APPLY CHANGES we use the "sqlmigrate" command 
#Syntax: python .\manage.py sqlmigrate [filename] [number of the file that is shown in the makemigrations command ex:0001]

#To finally specify all the final migration changes we run this command -python manage.py migrate [file name]

#This makes the database and the description of it stated in models.py are up to date!


#Create an admin user for our site wich is gonna be stored in the database, which will be used to perfrom adminstriatve functions
#such as adding data to the database


#To create the admin user, run "python manage.py createsuperuser"